version: 2
executorType: docker

containerInfo:
  - image: ruby:2.3.3
  - image: mysql:5.6
    env:
      MYSQL_ROOT_PASSWORD: pass

stages:
  build:
    workDir: /home/ubuntu/nippo
    steps:
      - type: checkout

      - type: shell
        name: Install System Dependencies
        command: apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

      - type: shell
        name: Install Ruby Dependencies
        command: bundle install

      - type: shell
        name: Create DB
        command: bundle exec rake db:create db:schema:load --trace

      - type: shell
        name: Run rubocop
        command: bundle exec rubocop

      - type: shell
        name: Run rspec
        command: bundle exec rspec spec --format progress --format RspecJunitFormatter --out tmp/rspec.xml
