db:
  name: nippo
  host: 127.0.0.1
  port: 3306
  user: root
  pass: pass

auth:
  use_whitelist: false

template:
  default:
    subject: 【日報】%s 部署 名前
    body: |
      ■雑感

      -----------------------------------------------------------------------------------
      ■本日の目標 / 達成状況

      ---------------------------------------------------------------------------------
      ■翌営業日の目標

      ----------------------------------------------------------------------------------
      ■プロフィール
      部署 名前（フロア 内線）
      ・スローガン
      　
      ・カオナビURL
      　
      -----------------------------------------------------------------------------------

      署名
